

export enum ThunksAction {
    CREATE_REWARD = 'CREATE_REWARD',
    GET_REWARDS = 'GET_REWARDS',
    GET_GAMES = 'GET_GAMES',
    GET_CHALLENGE_TYPES = 'GET_CHALLENGE_TYPES',
    GET_CHALLENGES = 'GET_CHALLENGES',
    CREATE_CHALLENGES = 'CREATE_CHALLENGES',

    GET_PROTECTED_RESOURCES = 'GET_PROTECTED_RESOURCES',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    LOGIN_EXISTING_TOKEN = 'LOGIN_EXISTING_TOKEN',

}